version: "3.7"
services:
  db:
    image: postgres:16
    container_name: db_app
    command: -p 1337
    expose:
      - 1337
    env_file:
      - .env-prod

  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: fastapi_app
    command: ["/сае/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db